name: 'Build Android projects'
description: 'A full-fledged environment for Android builds'
author: 'Harsh Shandilya (msfjarvis)'
inputs: 
  gradleTasks:
    description: 'Gradle tasks to run - If you want to run ./gradlew assemble, specify assemble here. '
    default: 'assembleDebug'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gradleTasks }}
